NAME := sup-world
MAKEFILE_INCLUDE_DIR ?= ../makefiles

include $(MAKEFILE_INCLUDE_DIR)/common.mk

# Extension example: add extra steps to install target
install::
	@echo "Installing additional sup-world requirements..."
